### PR TITLE
Ensure all log messages appear in Kinesis Stream

### PR DESCRIPTION
**Pull request by kenoir**
Trying to resolve the issue where not all logs are recorded to centralised logging service.

### CODE REVIEW

**Comment by kenoir** [comment]
Tested in CODE. All log messages now appearing!

**Comment by kenoir** [comment]
Ping @theefer.

**Comment by theefer** [comment]
w00t! What was the issue?

Also do all the logs show up in the logfiles on the apps? I noticed there is no more application.log, only stdout.log now?

**Comment by kenoir** [comment]
There are a couple of loggers being used by play (framework & app level). The previous code only directed app logs to kinesis, this captures the root logger and sends all logs.

We do not log to a file appender only to console (however our upstart script directs stdout to `stdout.log` :astonished:).

**Comment by theefer** [comment]
Ah OK. Would it be possible (or sensible) to write to disk as well, do you think?

**Comment by kenoir** [comment]
Possibly. I think log rotation is already taken of for media-service apps by logrotate.d config we previously set up. 

I'd lean towards doing that in another PR as it is another modification to existing behavior.

**Comment by theefer** [comment]
Yep that fine. :+1: 

I'm just thinking of us looking rather stupid if we have issues and Logstash is down and we have 0 logs.

**Comment by kenoir** [comment]
Turns out as logback is configure to push all logs (at debug level to STDOUT) and our upstart script pipes that to stdout.log (and logrotate.d already takes care of these logs) we should not need to make further changes.

**Pull request merged**
