### PR TITLE
use filename if description is missing

### PR DESCRIPTION
**Pull request by jamesgorrie**
A bit stateful, but this whole bit is really.

Waiting to hear back from Jo if certain characters often represent spaces, but we could add that later once she's used it as an iteration.

### CODE REVIEW

**Comment by akash1810** [comment]
:+1:

**Comment by paperboyo** [comment]
Bam! Filenames! Yessss. (Now we need them only when description is not missing :wink:).

**Comment by jamesgorrie** [comment]
@paperboyo  that's what happens.

**Comment by paperboyo** [comment]
@jamesgorrie So will filenames show up in search and in Show all metadata for _all_ images I upload (also the ones with the description)?

**Comment by jamesgorrie** [comment]
No. Filenames aren't used in any indexing that we do.
What happens here is, if you upload a file, and it has no description, we use the filename as a fallback.

**Comment by paperboyo** [comment]
Half way there, then :stuck_out_tongue_winking_eye:

**Comment by jamesgorrie** [comment]
Not really - I don't think we have any plans to include it in the metadata.

**Comment by paperboyo** [comment]
I know you don‘t. But the above fallback also was not planned. Filenames are/may be useful (e.g. inferring a correct CMYK profile from Imaging output reuploaded to Library).

I know that for the engineers of the newest stealth fighter it’s an abomination to include a hook. But it becomes useful when you have to tow it to the nearest gas station in case of a nuclear war.

**Comment by kenoir** [comment]
Best analogy ever.

On Wed, 15 Jul 2015 18:09 Mateusz <notifications@github.com> wrote:

> I know you don‘t. But the above fallback also was not planned. Filenames
> are/may be useful (e.g. inferring a correct CMYK profile from Imaging
> output reuploaded to Library).
>
> I know that for the engineers of the newest stealth fighter it’s an
> abomination to include a hook. But it becomes useful when you have to tow
> it to the nearest gas station in case of a nuclear war.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/937#issuecomment-121681833>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
