### PR TITLE
what's one more terrible hack between friends (hit the root api every fifteen minutes so google auth doesn't time out)

### PR DESCRIPTION
**Pull request by AWare**
pr description left blank from shame

### CODE REVIEW

**Comment by twrichards** [comment]
amazing if this works, but would be not better to do something server side on all API endpoints (which presumably fail when auth is expired) which do whatever the root endpoint is doing?

**Comment by AWare** [comment]
the root endpoint isn't doing anything special here, they all fail in the same way (with a 419), which causes pandular to force a reauth (because it wraps $http) 

if the auth session has timed out _a little_, then we can silently recover, but if it's too long, then we need to do an interactive reauth. the aim here is to not let the grid go too long without hitting an auth'd endpoint and thus timing out for the silent reauth

**Comment by twrichards** [comment]
> the root endpoint isn't doing anything special here, they all fail in the same way (with a 419), which causes pandular to force a reauth (because it wraps $http)
> 
> if the auth session has timed out _a little_, then we can silently recover, but if it's too long, then we need to do an interactive reauth. the aim here is to not let the grid go too long without hitting an auth'd endpoint and thus timing out for the silent reauth

makes sense, thanks for the explanation, with that said is their a lighterweight endpoint we could hit?

**Comment by AWare** [comment]
I think it would be unlikely/premature to do so.

**Review by twrichards — APPROVED** [review]

**Pull request merged**
