### PR TITLE
optimised blocked cookie image

### PR DESCRIPTION
**Pull request by akash1810**
Per https://github.com/guardian/grid/pull/1483#issuecomment-160306739

cc @paperboyo

### CODE REVIEW

**Comment by tsop14** [comment]
:+1:

**Comment by paperboyo** [comment]
Thanks!

**Comment by jamesgorrie** [comment]
Is it worth putting it in context of the omnibar?

**Comment by akash1810** [comment]
> Is it worth putting it in context of the omnibar?

Yep. Slightly related, [Google's doc](https://support.google.com/chrome/answer/95647?hl=en-GB) simply states

> an icon appears at the end of the address bar.

**Pull request merged**
