### PR TITLE
Perform DELETE request on uploads page when applying no labels.

### PR DESCRIPTION
**Pull request by akash1810**
Fixes https://github.com/guardian/grid/issues/931.

delete-all-labels

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Are we sure we want to do this? At least without confirmation as you could make a big :hankey: here?

**Comment by akash1810** [comment]
> Are we sure we want to do this?
I thought we decided it was a good feature to have here - https://github.com/guardian/grid/pull/925

**Comment by jamesgorrie** [comment]
Indeed - wandering if we should have a confirmation on this?

**Comment by jamesgorrie** [comment]
I suppose the question is are you happy to have this as a feature without a confirmation until someone messes up?

Has someone asked for this?

**Comment by akash1810** [comment]
> I suppose the question is are you happy to have this as a feature without a confirmation until someone messes up?

No. WIPing whilst I add that.

**Comment by jamesgorrie** [comment]
Besides the new colour - :

**Comment by jamesgorrie** [comment]
:+1:

**Pull request merged**
