### PR TITLE
[wip] Media api usage filter

### PR DESCRIPTION
**Pull request by akash1810**
Builds on https://github.com/guardian/grid/pull/1447. As that PR hasn't been merged, the diff on this PR looks huge. The only applicable code change is https://github.com/guardian/grid/commit/73f4d75ff84ba95ff547dd82329772e388a82b12.

### CODE REVIEW

**Comment by theefer** [comment]
:+1: for commit mentioned, modulo minor comment

**Comment by akash1810** [comment]
blocked awaiting https://github.com/guardian/grid/pull/1447 to be merged.

**Comment by jamesgorrie** [comment]
Given that we're differentiating between usage types - could we have filters work off `hasUsageType=web`? We can then compose all usage from this i.e. `hasUsageType=web,print`. It's a mistake we made with cost filter as a boolean.

**Comment by akash1810** [comment]
> Given that we're differentiating between usage types - could we have filters work off `hasUsageType=web`?

Yep, makes sense. Also follows how we've done `hasIdentifier` too.

**Comment by akash1810** [comment]
Closing as too far behind master and will be simpler to start on a new, up-to-date, branch.

**Pull request closed without merging**
