### PR TITLE
Show specialInstructions in metadata panel

### PR DESCRIPTION
**Pull request by theefer**
Special instructions sometimes contains crucial rights information so we need to display it.

image

Note in the above that specialInstructions is also a prefix of the description. A further task will be to strip it from the description if found there, to avoid unnecessary noise.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
By making this editable - are we not duplicating the restrictions?

**Comment by theefer** [comment]
I think the risk is minimal because you can only edit an existing special
instructions, not add one. This change follows issues where pictures had
important special instructions that weren't visible in the Grid.

On Thu, 9 Jul 2015 13:58 James Gorrie <notifications@github.com> wrote:

> By making this editable - are we not duplicating the restrictions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/888#issuecomment-119953463>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by jamesgorrie** [comment]
Cool - I was wondering if we just surface them - not make them editable - although I recon that would be more problematic.

:

**Comment by jamesgorrie** [comment]
:+1:

**Comment by theefer** [comment]
A few updates to merge master in and make it batch-editable via search like description and other fields.

**Pull request merged**
