### PR TITLE
Upgrade JSPM to 0.16

### PR DESCRIPTION
**Pull request by theefer**
Currently spitting some warnings some awaiting clarification via https://github.com/jspm/jspm-cli/issues/1015

Will remove the `ci` task altogether from the TC build step once this is merged.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
:+1:

**Comment by jamesgorrie** [comment]
Reading the title and looking at the code you have 7 vs 6?

**Comment by theefer** [comment]
Semver magic. To be precise it should be 6+ in the title.

On Thu, 13 Aug 2015 09:10 James Gorrie <notifications@github.com> wrote:

> Reading the title and looking at the code you have 7 vs 6?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/1072#issuecomment-130570487>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by jamesgorrie** [comment]
Just wondering if that was your intention :+1:

**Comment by theefer** [comment]
Yes, but the build seems a little broken atm.

**Comment by theefer** [comment]
So this is broken when bundling due to:

https://github.com/jspm/jspm-cli/issues/1019

Waiting for next JSPM release.

**Comment by theefer** [comment]
The bundling path issue is now fixed in the stable 0.16 version, so we should be safe to upgrade and this is ready for a final review. I'll test on TEST.

**Comment by theefer** [comment]
Also patch upgraded traceur.

**Pull request merged**
