### PR TITLE
Isolate scope in gr-preset-labels.

### PR DESCRIPTION
**Pull request by akash1810**
Fixes bug where the upload button does not work on the uploads page.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
:+1: for the fix.

What's actually happening though?

**Comment by akash1810** [comment]
> What's actually happening though?

Steps to reproduce problem:
- Visit `/upload`.
- Press Upload button.
- Choose file.
- Witness nothing happen (no file uploaded, not console logs).

**Comment by jamesgorrie** [comment]
Yip, get the interface problem, but why did this help?

**Comment by akash1810** [comment]
Ah, sorry! Without an isolated scope, [`ctrl.latestJob`](https://github.com/guardian/grid/blob/master/kahuna/public/js/upload/controller.js#L14) (also [here](https://github.com/guardian/grid/blob/master/kahuna/public/js/upload/view.html#L21)) gets removed. Similar solution was added to [`prompt`](https://github.com/guardian/grid/blob/master/kahuna/public/js/upload/prompt/prompt.js#L15) too.

**Pull request merged**
