### PR TITLE
A few more icons.

### PR DESCRIPTION
**Pull request by akash1810**
Working on the UI for #940 adds a new icon somewhere to the search page thumbnails - might as well update these couple icons too.

screen shot 2015-07-17 at 11 55 04

### CODE REVIEW

**Comment by alastairjardine** [comment]
This is really nice. Thanks for picking this up.

Since we're in the space, any chance we could change .image-action {…, border-top:1px dashed rgba(255, 255, 255, .5);} to solid? It'll reduce visual interference just a little bit. Happy to do a PR myself though if you think I'm being lazy.

**Comment by alastairjardine** [comment]
Also, can we add a hover state?

**Comment by alastairjardine** [comment]
Actually, it's probably a separate PR at this stage!

**Comment by akash1810** [comment]
> Also, can we add a hover state?

hover

**Comment by jamesgorrie** [comment]
Bonza - :+1:

**Comment by alastairjardine** [comment]
Boom. Will PR up the to solid line thing myself :) :+1:

**Pull request merged**
