### PR TITLE
place date picker relative to calling button

### PR DESCRIPTION
**Pull request by ShaunYearStrong**
Fixes Johnny's problem with the data picker overlay positioning

picture 97
picture 98

### CODE REVIEW

**Comment by kenoir** [comment]
:+1:

**Comment by kenoir** [comment]
Reverted as this causes:

screenshot from 2016-08-11 14-05-41

**Comment by ShaunYearStrong** [comment]
@kenoir Ooops, right you are. Need to look at that z-index.

**Comment by ShaunYearStrong** [comment]
@kenoir - I've fixed this problem *but* Removing the overflow means that when the panel contents go over a certain height, they become inaccessible. 

I'm not sure there's a great solution here to be honest, aside from calculating the date picker's position with JS on init.

**Pull request merged**
