### PR TITLE
Using ini file for settings as its simpler.

### PR DESCRIPTION
**Pull request by akash1810**
.ini files are slightly more universal than .py files and running `./main.py` is a lot easier - see the [readme](https://github.com/guardian/grid/blob/aa-dot-props/scripts/dot-properties/README.md)

### CODE REVIEW

**Comment by kenoir** [comment]
:+1:

**Comment by kenoir** [comment]
How does this fit with keeping some of this config in S3?

**Comment by akash1810** [comment]
> How does this fit with keeping some of this config in S3?

Similar to before - copy down one single file, add your stack name, run script.

Similar as its now one file, vs two - however ini files are friendlier imo.

**Comment by theefer** [comment]
:+1:

**Pull request merged**
