### PR TITLE
Add pluggable usage rights configuration

### PR DESCRIPTION
**Pull request by ochiengolanga**
## What does this change?

Introduce the ability to plug in your own usage rights configuration provider. Allowing other adopters to specify their own sources e.g. external database, configuration file, values in code e.t.c by creating their own providers.

This is achieved by introducing a new `UsageRightsConfigProvider` - a class that provides usage configuration. Two implementations are provided. One is the `GuardianUsageRightsConfig` - which has hardcoded configuration in code that mimics what was done before. The second is the `RuntimeUsageRightsConfig` that fetches the data from the application configuration.

- The new configuration will look similar as shown below.

To use the hardcoded configuration:
```hocon
usageRightsConfigProvider = "com.gu.mediaservice.lib.guardian.GuardianUsageRightsConfig$"
```

- To use configuration from the application configuration files:

```hocon
usageRightsConfigProvider {
  className: "com.gu.mediaservice.lib.config.RuntimeUsageRightsConfig"
  config {
    externalStaffPhotographers = [ # list of external staff photographers grouped by publication
      {
        name = "Publication 1",
        photographers = ["John Doe"]
      }
      {
        name = "Publication 2",
        photographers = ["Larry Wolf"]
      }
      {
        name = "Publication 3",
        photographers = ["Hafeez Jackson"]
      }
    ]
    internalStaffPhotographers = [ # list of internal staff photographers grouped by publication
      {
        name = "Publication 1",
        photographers = ["Jane Doe"]
      }
    ]
    contractedPhotographers = [ # list of contracted photographers grouped by publication
      {
        name = "Contract Photographers 1",
        photographers = ["Peter Larry"]
      }
    ]
    contractIllustrators = [ # list of contracted illustrators grouped by publication
      {
        name = "Contract Illustrators 1",
        photographers = ["Tom Hardy"]
      }
    ]
    staffIllustrators = ["John Doe", "Jane Doe", "Larry Wolf"] # list of staff illustrators
    creativeCommonsLicense = [ # list of allowed creative commons licenses
      "CC BY-4.0",
      "CC BY-SA-4.0",
      "CC BY-ND-4.0"
    ]
  }
}
```

Introduces the ability for an adopter to specify a list of usage rights that are applicable. This is achieved via configuration as shown below.

```hocon
usageRights.applicable = [
  "com.gu.mediaservice.model.NoRights",
  "com.gu.mediaservice.model.Handout",
  "com.gu.mediaservice.model.PrImage",
  "com.gu.mediaservice.model.Screengrab",
  "com.gu.mediaservice.model.SocialMedia",
  "com.gu.mediaservice.model.Agency",
  "com.gu.mediaservice.model.CommissionedAgency",
  "com.gu.mediaservice.model.Chargeable",
  "com.gu.mediaservice.model.Bylines",
  "com.gu.mediaservice.model.StaffPhotographer",
  "com.gu.mediaservice.model.ContractPhotographer",
  "com.gu.mediaservice.model.CommissionedPhotographer",
  "com.gu.mediaservice.model.CreativeCommons",
  "com.gu.mediaservice.model.GuardianWitness",
  "com.gu.mediaservice.model.Pool",
  "com.gu.mediaservice.model.CrownCopyright",
  "com.gu.mediaservice.model.Obituary",
  "com.gu.mediaservice.model.ContractIllustrator",
  "com.gu.mediaservice.model.CommissionedIllustrator",
  "com.gu.mediaservice.model.StaffIllustrator",
  "com.gu.mediaservice.model.Composite",
  "com.gu.mediaservice.model.PublicDomain"
]

```

Link to proposal [#3256](https://github.com/guardian/grid/issues/3256)

## How can success be measured?

From the sample configuration

```hocon
usageRights.applicable = [
  "com.gu.mediaservice.model.NoRights",
  "com.gu.mediaservice.model.Handout",
  "com.gu.mediaservice.model.PrImage",
  "com.gu.mediaservice.model.Screengrab",
  "com.gu.mediaservice.model.SocialMedia",
  "com.gu.mediaservice.model.Agency",
  "com.gu.mediaservice.model.CommissionedAgency",
  "com.gu.mediaservice.model.Chargeable",
  "com.gu.mediaservice.model.Bylines",
  "com.gu.mediaservice.model.StaffPhotographer",
  "com.gu.mediaservice.model.ContractPhotographer",
  "com.gu.mediaservice.model.CommissionedPhotographer",
  "com.gu.mediaservice.model.CreativeCommons",
  "com.gu.mediaservice.model.GuardianWitness",
  "com.gu.mediaservice.model.Pool",
  "com.gu.mediaservice.model.CrownCopyright",
  "com.gu.mediaservice.model.Obituary",
  "com.gu.mediaservice.model.ContractIllustrator",
  "com.gu.mediaservice.model.CommissionedIllustrator",
  "com.gu.mediaservice.model.StaffIllustrator",
  "com.gu.mediaservice.model.Composite",
  "com.gu.mediaservice.model.PublicDomain"
]

usageRightsConfigProvider {
  className: "com.gu.mediaservice.lib.config.RuntimeUsageRightsConfig"
  config {
    externalStaffPhotographers = [ # list of external staff photographers grouped by publication
      {
        name = "Publication 1",
        photographers = ["John Doe"]
      }
      {
        name = "Publication 2",
        photographers = ["Larry Wolf"]
      }
      {
        name = "Publication 3",
        photographers = ["Hafeez Jackson"]
      }
    ]
    internalStaffPhotographers = [ # list of internal staff photographers grouped by publication
      {
        name = "Publication 1",
        photographers = ["Jane Doe"]
      }
    ]
    contractedPhotographers = [ # list of contracted photographers grouped by publication
      {
        name = "Contract Photographers 1",
        photographers = ["Peter Larry"]
      }
    ]
    contractIllustrators = [ # list of contracted illustrators grouped by publication
      {
        name = "Contract Illustrators 1",
        photographers = ["Tom Hardy"]
      }
    ]
    staffIllustrators = ["John Doe", "Jane Doe", "Larry Wolf"] # list of staff illustrators
    creativeCommonsLicense = [ # list of allowed creative commons licenses
      "CC BY-4.0",
      "CC BY-SA-4.0",
      "CC BY-ND-4.0"
    ]
  }
}
```

## Screenshots
The below screenshots show the available list of illustrators, photographers and creative commons licenses from the configuration above.

#### Contract Illustrator usage right
Upload form - Contract Illustrator usage right

#### Contract Photographer usage right
Upload form - Contract Photographer usage right

#### Creative Commons usage right
Upload form - Creative Commons usage right

#### Staff Illustrator usage right
Upload form - Staff Illustrator usage right

#### Staff Photographer usage right
Upload form - Staff Photographer usage right

## Who should look at this?

@sihil , @akash1810 and @paperboyo

## Tested?
- [X] locally by committer
- [ ] locally by Guardian reviewer
- [ ] on the Guardian's TEST environment

### CODE REVIEW

**Comment by AWare** [comment]
I guess this will require translation of the current photographer data as config before it can be merged?

**Comment by ochiengolanga** [comment]
@AWare Yes. Or else photographers, illustrators and creative commons licenses will be an empty list. Here's a shortened version of how the configuration would look like for The Guardian

```hocon
photographers {
  externalStaffPhotographers = [ # list of external staff photographers grouped by publication
    {
      name = "The Guardian",
      photographers = ["Ben Doherty", "Bill Code", ...]
    }
    {
      name = "The Observer",
      photographers = ["David Newell Smith", ...]
    }
  ]
  internalStaffPhotographers = [ # list of internal staff photographers grouped by publication
    {
      name = "The Guardian",
      photographers = ["E Hamilton West", ...]
    }
  ]
  contractedPhotographers = [ # list of contracted photographers grouped by publication
    {
      name = "The Guardian",
      photographers = ["Alicia Canter", ...]
    }
    {
      name = "The Observer",
      photographers = ["Andy Hall", ...]
    }
  ]
  contractIllustrators = [ # list of contracted illustrators grouped by publication
    {
      name = "The Guardian",
      photographers = ["Ben Lamb", ...]
    }
  ]
  staffIllustrators = ["Guardian Design"] # list of staff illustrators
  creativeCommonsLicense = [ # list of allowed creative commons licenses
    "CC BY-4.0",
    "CC BY-SA-4.0",
    "CC BY-ND-4.0"
  ]
}
```

**Comment by paperboyo** [comment]
Hi, just been testing this. Everything looks good in guardianland, apart from one thing: the alphabetical order in TEST follows the [code](https://github.com/guardian/grid/blob/f7d469a67f90682f2f5e71f3fab2de9d1365cfb6/common-lib/src/main/scala/com/gu/mediaservice/lib/config/MetadataConfig.scala#L44-L78): `// Current` first `// Past` following, while it’s all-alphabetical in PROD (“merging” `// Current` and `// Past`) from code:

PROD (how it should be, whole list is sorted together):

PROD

TEST (order is not all-alphabetical):

TEST

**Comment by ochiengolanga** [comment]
Thanks for the review @paperboyo I'll be sorting that out shortly

**Comment by ochiengolanga** [comment]
@paperboyo addressed concern on sorting of photographers.

**Comment by paperboyo** [comment]
I have tested UI for these

    externalStaffPhotographers
    internalStaffPhotographers
    contractedPhotographers
    staffIllustrators
    contractIllustrators
    creativeCommonsLicense 

and all is correct, incl. the sorting (thanks!). Ready for (code) review.

**Review by AWare — APPROVED** [review]

**Comment by paperboyo** [comment]
Closes https://github.com/guardian/grid/issues/3256.

**Pull request merged**
