### PR TITLE
style uploading and recent uploads the same.

### PR DESCRIPTION
**Pull request by akash1810**
Also styling uploading images the same as recently uploaded images for consistency.

style

### CODE REVIEW

**Comment by theefer** [comment]
Weird header in your screen cast above the failed image thumbnail?

**Comment by akash1810** [comment]
@theefer nope, poor choice of image on my part - the image is an old screenshot of the grid :blush: 

Updated.

**Comment by jamesgorrie** [comment]
> the image is an old screenshot of the grid

**Comment by akash1810** [comment]
grr, I thought I updated the gif already?!?!

style

**Comment by theefer** [comment]
Slightly worried that the "Status" isn't very prominent in the new version. Is that a problem?

Does this address the issue with uploading unsupported files preventing further uploads?

**Comment by akash1810** [comment]
> Does this address the issue with uploading unsupported files preventing further uploads?

Not yet. My intention is that you'd click Delete on any failed upload, and if the size of the upload job becomes 0, the prompt will appear again. Writing this down, I realise I'm mixing intents in this PR :disappointed:

**Comment by akash1810** [comment]
closing - will raise a different PR with just the delete button.

**Pull request closed without merging**
