### PR TITLE
Change Reponse to Response with two 's's

### PR DESCRIPTION
**Pull request by satterly**
Fix typo. "Response" has two "s"s, not one.

### CODE REVIEW

**Comment by kenoir** [comment]
:laughing:

**Comment by NickPapacostas** [comment]
👍  tested locally, will test on TEST and merge ^_^ thanks @satterly

**Comment by NickPapacostas** [comment]
Ok tested deploying various apps with this branch and it looks all good. I'm thinking we can just merge it and not deploy everything as it doesn't seem to matter.

@akash1810 does that sound ok to you?

**Comment by akash1810** [comment]
I would deploy it to keep things simple - PROD should reflect the head of master.

**Comment by kenoir** [comment]
@NickPapacostas any reason this didn't go out?

**Comment by NickPapacostas** [comment]
:( nope

**Pull request merged**
