### PR TITLE
Add a search icon to the search field which acts as the syntax toggle.

### PR DESCRIPTION
**Pull request by akash1810**
Now the ordering is in the top toolbar, this creates a some space.

advanced-icon

### CODE REVIEW

**Comment by kenoir** [comment]
Nice!

Perhaps this should only happen at smaller widths though, to make it more
easily discoverable?

On Fri, 21 Aug 2015 at 00:12 Akash A <notifications@github.com> wrote:

> Now the ordering is in the top toolbar, this creates a some space.
>
> [image: advanced-icon]
> <https://cloud.githubusercontent.com/assets/836140/9397903/466f23aa-4799-11e5-9414-69f19f53fd46.gif>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/guardian/grid/pull/1124
> Commit Summary
>
>    - Add a search icon to the search field which acts as the syntax
>    toggle.
>
> File Changes
>
>    - *M* kahuna/public/js/search/query.html
>    <https://github.com/guardian/grid/pull/1124/files#diff-0> (17)
>    - *M* kahuna/public/stylesheets/main.css
>    <https://github.com/guardian/grid/pull/1124/files#diff-1> (31)
>
> Patch Links:
>
>    - https://github.com/guardian/grid/pull/1124.patch
>    - https://github.com/guardian/grid/pull/1124.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/1124>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by alastairjardine** [comment]
I worry that there is a wider implication that advanced suddenly becomes
undiscoverable, even with a disclosure triangle added (which should be
added if you do release)

--
Alastair Jardine, Senior UX Architect

On 21 August 2015 at 08:27, Robert Kenny <notifications@github.com> wrote:

> Nice!
>
> Perhaps this should only happen at smaller widths though, to make it more
> easily discoverable?
>
> On Fri, 21 Aug 2015 at 00:12 Akash A <notifications@github.com> wrote:
>
> > Now the ordering is in the top toolbar, this creates a some space.
> >
> > [image: advanced-icon]
> > <
> https://cloud.githubusercontent.com/assets/836140/9397903/466f23aa-4799-11e5-9414-69f19f53fd46.gif
> >
> > ------------------------------
> > You can view, comment on, or merge this pull request online at:
> >
> > https://github.com/guardian/grid/pull/1124
> > Commit Summary
> >
> > - Add a search icon to the search field which acts as the syntax
> > toggle.
> >
> > File Changes
> >
> > - *M* kahuna/public/js/search/query.html
> > <https://github.com/guardian/grid/pull/1124/files#diff-0> (17)
> > - *M* kahuna/public/stylesheets/main.css
> > <https://github.com/guardian/grid/pull/1124/files#diff-1> (31)
> >
> > Patch Links:
> >
> > - https://github.com/guardian/grid/pull/1124.patch
> > - https://github.com/guardian/grid/pull/1124.diff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/guardian/grid/pull/1124>.
> >
>
> --
>
> ------------------------------
> Visit theguardian.com. On your mobile and tablet, download the Guardian
> iPhone and Android apps theguardian.com/guardianapp and our tablet
> editions
> theguardian.com/editions. Save up to 57% by subscribing to the Guardian
> and Observer - choose the papers you want and get full digital access.
> Visit subscribe.theguardian.com
>
> This e-mail and all attachments are confidential and may also be
> privileged. If you are not the named recipient, please notify the sender
> and delete the e-mail and all attachments immediately. Do not disclose the
> contents to another person. You may not use the information for any
> purpose, or store, or copy, it in any way. Guardian News & Media Limited
> is not liable for any computer viruses or other material transmitted with
> or as part of this e-mail. You should employ virus checking software.
>
> Guardian News & Media Limited is a member of Guardian Media Group plc.
> Registered
> Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.
> Registered
> in England Number 908396
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/1124#issuecomment-133314950>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by theefer** [comment]
Also doesn't seem as discoverable to me. If we're desperate to save space, could we collapse the `> advanced` into just an obvious icon, maybe [cogwheel](https://www.google.com/design/icons/#ic_settings)?

**Comment by theefer** [comment]
OTOH having the search icon in the search field (unrelated to advanced syntax) might be nice.

**Comment by akash1810** [comment]
Looks like discoverability is the main concern, which I agree with (closing PR). We don't seem to be tracking usage of the advanced toggle, should we? I fear it might be very noisy...

**Comment by alastairjardine** [comment]
I do like the search icon in there keep that! – just concerned that the advanced is a bit of a stretch.

**Comment by akash1810** [comment]
> I do like the search icon in there keep that!

separate PR is on the way

**Comment by theefer** [comment]
> We don't seem to be tracking usage of the advanced toggle, should we?

Yes. Don't think it'll be particularly noisy.

**Comment by paperboyo** [comment]
> even with a disclosure triangle added

I like the idea of magnifying glass + triangle. Seems quite standard. Should be discoverable enough, IMHO. And saves space/cuts noise.

After the accompanying PR (https://github.com/guardian/grid/issues/1127) is out the icon behaves like a piece of text, though - it can be "selected" like so:

search_icon

Also, the new clear search x button is too low. Not as low as it was, but still too low. And I'm pedantic. Not as pedantic as in, say, 15 years time, but still pedantic.

too low

Thanks!

**Pull request closed without merging**
