### PR TITLE
Filters deleted collections from collection children

### PR DESCRIPTION
**Pull request by SHession**
## What does this change?
This PR aims to fix the issue whereby all sub-collections wouldn't render if there was an orphaned sub-collection.

## How can success be measured?
When an orphaned sub-collection exists, the other collections still render correctly.

## Tested?
- [x] locally
- [ ] on TEST

### CODE REVIEW

**Comment by paperboyo** [comment]
cc @akash1810 for an opinion. My only worry is that this may hide the instances of errors, so we may be not alerted to them as currently only user feedback is responsible for alerting us. Granted, using users as reporting device is a bit 👿 .

**Comment by SHession** [comment]
> cc @akash1810 for an opinion. My only worry is that this may hide the instances of errors, so we may be not alerted to them as currently only user feedback is responsible for alerting us. Granted, using users as reporting device is a bit 👿 .

There was a [separate PR](https://github.com/guardian/grid/pull/3073) to add logging for this issue on the server side. Therefore, we should still be able to tell when it happens.

**Review by akash1810 — COMMENTED** [review]
Should this be done server side? Having this done client side suggests the server's response is correct, for some use cases - is that right?

**Review by AWare — APPROVED** [review]

**Comment by SHession** [comment]
@akash1810, @AWare has attempted to implement this fix on the server side and found it to be much more complicated. This fix should be beneficial for now and we can remove it as/when we implement the server fix.

**Pull request merged**
