### PR TITLE
Implement local providers for authentication and authorisation

### PR DESCRIPTION
**Pull request by adrielulanovsky**
## What does this change?
This PR implements a LocalAuthenticationProvider and a LocalAuthorisationProvider which lets everyone through anything with a generic user, for simplicity in local development. It also changes the setup script so that the application.conf file has the correct local providers when running locally.

## How can success be measured?
As a developer, when I'm running the grid locally I don't need to authenticate, and I have permissions for everything.

## Who should look at this?
@guardian/digital-cms @sihil @gribeiro @wainaina 

## Tested?
- [x] locally by committer
- [ ] locally by Guardian reviewer
- [ ] on the Guardian's TEST environment

### CODE REVIEW

**Comment by AWare** [comment]
I think this might be worth making optional.

**Comment by adrielulanovsky** [comment]
> I think this might be worth making optional.

We could use an environment variable in the setup script to use either this one or the previous one. Do you think the current one should be the default?

**Comment by AWare** [comment]
> We could use an environment variable in the setup script to use either this one or the previous one. Do you think the current one should be the default?

This seems reasonable.

**Comment by adrielulanovsky** [comment]
> I think this might be worth making optional.

I added checks for LOCAL_SIMPLE_AUTH_PROVIDER env variable. If that variable is true, the setup script will set the local authentication and authorisation providers. Otherwise, it will behave as it used to.

**Review by AWare — APPROVED** [review]

**Review by AWare — APPROVED** [review]
tested on TEST and am happy with it

**Pull request merged**
