### PR TITLE
remove ability to run scripts from thall

### PR DESCRIPTION
**Pull request by jamesgorrie**
Seems like a very dangerous thing to have lying around.
:boom:

### CODE REVIEW

**Comment by theefer** [comment]
I wanted to do that the other day and forgot, nice one :+1:

**Comment by theefer** [comment]
maybe don't release thrall now though

**Comment by theefer** [comment]
let's do that tomorrow morning rather than so late in the day

**Comment by jamesgorrie** [comment]
Thrall looks to have caught up with everything and is healthy - :ship:

**Pull request merged**
