### PR TITLE
allow the world to get objects in the image origin bucket

### PR DESCRIPTION
**Pull request by akash1810**
the one where crops go

### CODE REVIEW

**Comment by mbarton** [comment]
I'm not against this since it matches PROD behaviour but would people be suprised that their local dev crops were visible to the world?

**Comment by akash1810** [comment]
> I'm not against this since it matches PROD behaviour but would people be suprised that their local dev crops were visible to the world?

Yeah, its not great, I agree. We could add a condition for [`IpAddress`](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-3) or [`Referrer`](https://docs.aws.amazon.com/AmazonS3/latest/dev/example-bucket-policies.html#example-bucket-policies-use-case-4) to limit it to the office or Grid DEV? Not keen on the former as it wouldn't work for the community...

**Comment by mbarton** [comment]
I guess we could parameterise them in the cloud formation?

**Comment by RichieAHB** [comment]
That is a very good point @mbarton

**Comment by akash1810** [comment]
Updated in https://github.com/guardian/grid/pull/2418/commits/535dd31bc617e2a163f701a898580d4f67f65bfd. Not especially keen on it though as we diverge across stacks now...

Setting the referrer header will mean other Tools don't be able to link to DEV images, which isn't ideal.

**Comment by tonytw1** [comment]
Assuming that 'Image origin' referrs to the 'crops' bucket.

The UI accesses images in the thumbnail and full images buckets using authenticated S3 calls. UI references to the crop thumbnails are not authenticated because the crops bucket is intended to be public docroot.

If the UI authenticated it's crop bucket calls, even though the crop bucket is probably public in most deployments, would that resolve this while still accommodating the private crops bucket use case?

**Comment by mbarton** [comment]
Closing since the original problem was fixed by changing config so it's no longer required

**Pull request closed without merging**
