### PR TITLE
advanced syntax as a component.

### PR DESCRIPTION
**Pull request by akash1810**
The start of a little ui experiment I've got in mind around tooltips. These changes are granular enough to be separate though.

### CODE REVIEW

**Comment by alastairjardine** [comment]
Hmmm! Actions into the action bar?! :stuck_out_tongue:

**Comment by theefer** [comment]
:+1:

**Comment by akash1810** [comment]
@alastairjardine soon! I've started a branch for it.

**Comment by alastairjardine** [comment]
@akash1810 Yesssss *fist pumps*

**Comment by theefer** [comment]
fist pumps

(sorry, I had to)

**Pull request merged**
