### PR TITLE
graphicsmagick

### PR DESCRIPTION
**Pull request by tsop14**
Forces the use of graphicsmagick and removes reference to imagemagick in readme.

### CODE REVIEW

**Comment by theefer** [comment]
:+1:

**Comment by paperboyo** [comment]
Whoa. Could it affect our colour management logic? https://github.com/guardian/grid/pull/1281#issuecomment-141967950

@theefer

**Comment by theefer** [comment]
@paperboyo It didn't work with ImageMagick.

**Comment by paperboyo** [comment]
Sorry, I'm an idiot - it was GM from the beginning... Got a colour-management panic. Something akin to kernel one, I suppose.

**Pull request merged**
