### PR TITLE
Fix leaking and errors on image update

### PR DESCRIPTION
**Pull request by theefer**
1. We should always free global listeners in controllers.
2. imagesAll can contain holes (`undefined`) so we need to protect against it (else we're seeing `Cannot read property 'data' of undefined`)

### CODE REVIEW

**Comment by theefer** [comment]
Oddly the `image-updated` event seems to be triggered twice, not sure why.

**Comment by theefer** [comment]
Also added another fix for an error that occurs every time the gr-panel is closed.

**Comment by jamesgorrie** [comment]
:+1: Nice catches.

**Comment by jamesgorrie** [comment]
Standing by my :+1:

**Pull request merged**
