### PR TITLE
Shonkily restrict batch editing photoshoots

### PR DESCRIPTION
**Pull request by mbarton**
They currently have O(N!) behaviour and can bring down the Grid!

21432b593b56b8a52cacf8b1c7f735a2

### CODE REVIEW

**Comment by paperboyo** [comment]
How about adding `Editing photoshoots is *currently* not possible` to create incentive for developers to fix it? ;-)

I wonder: if it’s indeed not adding pics to photoshoot but the subsequent propagation of RCS rights to the said shoot, maybe we don’t have to do anything to upload page? (and maybe this here could be showing only if selection contains any RCS info; not worth redoing, though!)

**Comment by mbarton** [comment]
Yep I think we're fine to leave the upload page since people will have to edit the photoshoot of each image manually

**Comment by mbarton** [comment]
[Restrict batch editing of photoshoots to 10 images](https://trello.com/c/pTkNG9Fv/21-restrict-batch-editing-of-photoshoots-to-10-images)

**Comment by mbarton** [comment]
I went with `We are working to improve this`

**Pull request merged**
