### PR TITLE
Excludes stingray folder from ftp-watcher ingest

### PR DESCRIPTION
**Pull request by kenoir**
Removes `stringray` from ingested folders for ftp-watcher

### CODE REVIEW

**Comment by theefer** [comment]
:+1: are we confident that S3 ingestion is matching up (possibly even working better without all the ftp-watcher bugs)?

**Comment by kenoir** [comment]
I'm seeing some unusual behaviour in TEST so we should hold this until I can figure out what's going on.

**Comment by humaislam** [comment]
The plan is for them to do their work next week so worth keeping Adrian in
the loop if you do want to hold off

On 19 November 2015 at 15:03, Robert Kenny <notifications@github.com> wrote:

> I'm seeing some unusual behaviour in TEST so we should hold this until I
> can figure out what's going on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/1463#issuecomment-158082714>.
>



-- 
​Huma Islam

Agile project manager

Guardian News & Media

-----

huma.islam@theguardian.com

-----


Kings Place, 90 York Way,

London N1 9GU

theguardian.com

​-----

​​Download the Guardian app for Android
<https://play.google.com/store/apps/details?id=com.guardian&hl=en_GB> and
iOS​ <https://itunes.apple.com/gb/app/the-guardian/id409128287?mt=8>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by theefer** [comment]
Marked as blocked until the bug with filenames with two spaces not being uploaded to the S3 bucket is resolved.

**Pull request merged**
