### PR TITLE
Fix command to configure github registry on CI

### PR DESCRIPTION
**Pull request by theefer**
Hoping this will resolve the current failures to build kahuna on TC.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
So this has never worked?

:+1:

**Comment by theefer** [comment]
No I think it got renamed with a JSPM upgrade and somehow things still worked in the meantime, maybe because someone else (frontend?) was helping set this global auth on the TC box.

**Comment by theefer** [comment]
Ah JSPM 0.16 beta just got a new version out, likely related.

**Comment by theefer** [comment]
Not sure this branch has fixed the issue actually.

**Pull request merged**
