### PR TITLE
Update main.css

### PR DESCRIPTION
**Pull request by alastairjardine**
Removing dotted line to reduce visual interference
**Before**
screen shot 2015-07-20 at 11 36 12

**After**
screen shot 2015-07-20 at 11 35 55

### CODE REVIEW

**Comment by theefer** [comment]
Seems innocuous enough but where is this (screenshot?)?

**Comment by alastairjardine** [comment]
@theefer Updated main comment above.

**Comment by theefer** [comment]
:+1: 

(or they could even be transparent (margin instead of border)? either way removing the dashed line makes sense imo too)

**Comment by alastairjardine** [comment]
@theefer Yeah, it's just a bit cleaner. Unsure what you mean about border/margin?

**Comment by theefer** [comment]
I meant: should the separator be an actual coloured line, or should it just be a transparent gap? Just a thought, I don't particularly mind.

**Comment by alastairjardine** [comment]
Happy with just transparency for the sake of speed. Perhaps one for a refactor in the future (as @akash1810 & I have spoken about)

**Comment by akash1810** [comment]
If we're striving for consistency, should we also change the dashed separator on the uploads page? If so, transparent wouldn't work.

**Comment by alastairjardine** [comment]
Yep, but I thought that was pretty high up the agenda for rejiggery anyway?

**Comment by akash1810** [comment]
True, true.

**Comment by theefer** [comment]
Actually while the gap works on lighter background:

screenshot-2015-07-20t14 35 40

It's invisible on darker background:

screenshot-2015-07-20t14 35 32

So let's just ship @alastairjardine's version with the border for now, works more generally.

**Pull request merged**
