### PR TITLE
[WIP] Refresh client if out of sync with server 

### PR DESCRIPTION
**Pull request by kenoir**
This will force hard refresh the client if it sees a differing app
version on the server.

My suspicion is that forcing a refresh is a bit obnoxious and this
should probably just display a message when out of date.

### CODE REVIEW

**Comment by NickPapacostas** [comment]
Really nice code, I learned a lot from it.  (angular / node packaging, more observable examples to draw on, nice functional pipelining etc)

I guess my only concern would be that it's not a common enough issue to merit the potential maintenance requirements. 

:+1: :ideograph_advantage:

**Comment by akash1810** [comment]
How does this work if, for example, you're in the middle of a crop? It looks like the page would refresh without your consent?

**Comment by kenoir** [comment]
@akash1810 indeed it would. But if the UI is out of sync with API it could very well fail anyway.

**Comment by akash1810** [comment]
Depends on which API. _If_ auto refresh does becomes painful, could display a message on screen that you're out of date, prompting to refresh, for example.

:+1:

**Comment by akash1810** [comment]
Also, rather than polling, you could use [requestIdleCallback](https://developers.google.com/web/updates/2015/08/using-requestidlecallback?hl=en)

**Comment by kenoir** [comment]
This is going to stay on hold for a little while until we see another use case for it.

**Comment by kenoir** [comment]
Closing until we have a reason to do this.

**Pull request closed without merging**
