### PR TITLE
update to ng-1.4

### PR DESCRIPTION
**Pull request by jamesgorrie**
I remember opening this a while ago and can't remember if it got shot down.
I'll wait for the Rx stuff merge and test again too.

The reason for this is a want to start looking at the futuristic router.

### CODE REVIEW

**Comment by theefer** [comment]
:+1: but please let me ship the infinite scroll first, if possible, and also needs a thorough QA and review of the Changelog

**Comment by jamesgorrie** [comment]
Definitely.

I've been through the changelog and it looks like we've been following best practise so we've not used anything deprecated. 1.4 wasn't a massive release, but it does allow you to use the router (although it's not included).

**Comment by theefer** [comment]
Do you want to try, test and get this in today?

Let us know if you need help QA'ing the whole app before pushing to PROD.

**Comment by jamesgorrie** [comment]
Yip, merging master, this and traceur update and will push to TEST
.

**Comment by jamesgorrie** [comment]
Alls well, going to merge both this and traceur update.

**Pull request merged**
