### PR TITLE
Add Grid logo as 'Home' link at the top-right of every screen

### PR DESCRIPTION
**Pull request by theefer**
(Sorry for the PR spam, clearing some of my local branches before the BFG...)

This adds the current Grid logo/favicon @akemitakagi made as "home" link, as per every website on the Internet ever. This can also serves as an "escape" to reset any search query.

capture-2015-07-04t22 43 59

### CODE REVIEW

**Comment by theefer** [comment]
Note: rewrote the code now we have a shared top-bar component, much simpler cc @akash1810

**Comment by akash1810** [comment]
woo! :+1:

**Comment by theefer** [comment]
I tried adding "grid" as per Workflow but it looks redundant and consumes space for what seems little benefit. Going to ship without but we can add it if people feel it's worth the space and extra font loading (just for one word!).

Most importantly, the guidelines for consistency look like the right direction to me, and they consist in giving a contextual clue (e.g. search, image, uploads, rather than just "grid"). Adding that context should be possible (not sure how we do it for the window title, but something like that), but feels like extra complexity and possible bugs worth a separate PR.

image

image

**Comment by paperboyo** [comment]
> extra font loading

I just wanted to flag that using this font for whatever else than a couple of known words is asking for trouble. It doesn't have (and, most probably, never will) extended character set matching all other our fonts... And the fallbacks look **really** bad with it.

**Comment by akemitakagi** [comment]
Hi Mateusz,
Are you referring to the titlepiece?
If so we are only using the font for the name of the tool, so it is a
couple of known words.

The rest we use Egyptian Text and Agate sans.

Akemi

On Wednesday, July 8, 2015, Mateusz <notifications@github.com> wrote:

> extra font loading
>
> I just wanted to flag that using this font for whatever else than a couple
> of known words is asking for trouble. It doesn't have (and, most probably,
> never will) extended character set matching all other our fonts... And the
> fallbacks look *really* bad with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/907#issuecomment-119655079>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
Hi, Akemi,

Yes. Unfortunately, the foundry never completed the work on it and it would be a major undertaking to bring it to the standard of the rest. As it’s used currently in Tools seems entirely safe, I just wanted to flag that up, because I’ve seen it misused by some other teams.

Thanks!

Regards
Mateusz

**Comment by alastairjardine** [comment]
@theefer We should try to add in "search" where you had grid above. It's the primary purpose of the page…unless it isn't?!

**Comment by theefer** [comment]
That page yes, but this is on every page, so the text should be contextual,
as per the guidelines you posted.

This was just the first step. For the next step let's work on the
horizontal space of the search so as not to make it worse (see also Akash's
upload button PR).

On Thu, 9 Jul 2015 11:21 Alastair Jardine <notifications@github.com> wrote:

> @theefer <https://github.com/theefer> We should try to add in "search"
> where you had grid above. It's the primary purpose of the page…unless it
> isn't?!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/907#issuecomment-119900213>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Pull request merged**
