### PR TITLE
[WIP] adds jonny weeks to staff photographers list

### PR DESCRIPTION
**Pull request by tsop14**

### CODE REVIEW

**Comment by akash1810** [comment]
:+1:

**Comment by theefer** [comment]
Can we respect the alphabetical order for ease of maintenance? Apart from that :+1:

**Comment by jamesgorrie** [comment]
Still tentative from me - trying to figure out exactly what we're doing here - but if you think it solves an immediate problem that can be polished later :+1:

**Comment by tsop14** [comment]
Not a good idea to add someone to a list they should not be on.

**Pull request closed without merging**
