### PR TITLE
Extract Guardian specific messages into config

### PR DESCRIPTION
**Pull request by adrielulanovsky**
## What does this change?
Currently, there are many Guardian-specific messages in the UI. This is an effort to make these messages configurable.

The following are some of the things that BBC wants to customise:
- References to "the Grid" will be changed to "BBC Images".
- References to "The Guardian" will be changed to "BBC".
- References to "The Observer" will be changed to "BBC Studio".

Regarding the systemName config, I've noticed there's not a uniform capitalisation of it; some places it's written as "the grid", some as "the Grid", others as "The Grid". My approach was to default systemName to "the Grid" to avoid having to add 3 different configs for this value. However, there's one place where I had to capitalise the first letter via code, because it was at the start of a sentence.

In one place "Grid" was used without the article ("Grid-specific usage rights") so I decided to make that whole text configurable.

The other message I extracted completely was "Drop files or GuardianWitness URLs here to upload them instantly to the Grid". BBC wants this phrase to read as "Drop files or URLs here to upload them instantly to BBC Images".

Same thing for the usage of "Observer". One instance had lowercase while the other had uppercase first letter. I decided to use "Observer" as default value.

## Who should look at this?
@guardian/digital-cms

## Tested?
- [x] locally by committer
- [ ] locally by Guardian reviewer
- [x] on the Guardian's TEST environment

### CODE REVIEW

**Comment by AWare** [comment]
It might be easier to do these strings with some webpack magic instead of injecting into the html.

**Comment by adrielulanovsky** [comment]
> It might be easier to do these strings with some webpack magic instead of injecting into the html.

Sorry, I'm not too familiar with webpack. Do you mean extracting configuration into a file, like this? https://webpack.js.org/guides/asset-management/#loading-data. If that's the case, I think there's one instance (systemName) where this is used in the Scala template, so I'm not sure it can be replaced via webpack (unless there's more advanced magic that I'm not aware of). 

I can try to take that approach for the other variables though

**Comment by AWare** [comment]
I'm thinking we have a `strings.js` file and then set the replacements in that.

**Comment by adrielulanovsky** [comment]
> I'm thinking we have a `strings.js` file and then set the replacements in that.

I extracted most of the configs (except systemName, for the reason already mentioned) into a strings.json file

**Review by AWare — APPROVED** [review]

**Comment by paperboyo** [comment]
Tested, thanks, @adrielulanovsky!

**Pull request merged**
