### PR TITLE
Foreman procfile

### PR DESCRIPTION
**Pull request by NickPapacostas**
allows you to run all the apps from one command

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Is this different to [this](https://github.com/guardian/grid/blob/master/run.sh
)

**Comment by theefer** [comment]
run.sh only works on Linux. I don't mind the duplication as we explore better cross-platform ways to run the service. But yeah long term would be nice to have a single standard cross-platform way.

**Comment by NickPapacostas** [comment]
one other advantage is you can run services individually a bit easier e.g. "foreman run media-api"

**Comment by jamesgorrie** [comment]
:+1: bonza

**Pull request merged**
