### PR TITLE
Workaround for Play CSRF vulnerability

### PR DESCRIPTION
**Pull request by kenoir**
https://www.playframework.com/security/vulnerability/20160304-CsrfBypass

### CODE REVIEW

**Comment by kenoir** [comment]
Pinging @rrees.

**Comment by adamnfish** [comment]
Looks good, although you'll need to make sure this change doesn't break anything.

**Comment by kenoir** [comment]
Just going through it with @rrees.

**Comment by rrees** [comment]
:+1: just sat down and reviewed the app locally

**Pull request merged**
