### PR TITLE
Better mobile and responsive breakpoints

### PR DESCRIPTION
**Pull request by theefer**
Add meta-viewport tag to force viewport to device width (better on mobile), adjust breakpoints and more collapsing so search results are usable on a mobile phone.

Note that other screens (e.g. image preview, cropping) are not really.

# Before

recorded

# After

recorded

Not sure how scalable this approach to breakpoints is in the long run, but it's an easy win for now and it remains fairly isolated.

### CODE REVIEW

**Comment by akash1810** [comment]
Looks good. Should the search box be full width at this width:

screen shot 2015-08-04 at 10 41 02

**Comment by kenoir** [comment]
Nice!

Should the "settings" cog appear in the full width view so we can train desktop users what it means (and to be consistent with current icon/label pattern)?

**Comment by alastairjardine** [comment]
Minor things.
1. The cog suddenly appears at a breakpoint. I'd advocate attaching the icon to text buttons at all breakpoints so it's signposted and learnable
2. The dropdown feels superfluous

**Comment by alastairjardine** [comment]
@kenoir Yes – didn't see your message before posting mine.

**Comment by theefer** [comment]
> Should the search box be full width at this width?

Will check, might be a bit of a pain to get the width right without magic numbers to subtract from 100%. Might be easier with flexbox (though we had issues with nested flexbox performance in Composer).

**Comment by theefer** [comment]
@kenoir @alastairjardine Do we think the cog is the right icon to represent filters?

**Comment by alastairjardine** [comment]
Not sure it works brilliantly for filters, but it could also be relabelled
"advanced filtering", which is more cog-like.

--
Alastair Jardine, Senior UX Architect

On 4 August 2015 at 11:13, Sébastien Cevey <notifications@github.com> wrote:

> @kenoir <https://github.com/kenoir> @alastairjardine
> <https://github.com/alastairjardine> Do we think the cog is the right
> icon to represent filters?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/1018#issuecomment-127555805>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by theefer** [comment]
There is also https://www.google.com/design/icons/#ic_filter_list

**Comment by alastairjardine** [comment]
Seems like a reasonable choice!

**Comment by theefer** [comment]
Agree with the icon. Only question is whether having both the expander arrow and an icon looks weird (hint: it does):

image

**Comment by jamesgorrie** [comment]
Going on our conversation about retiring the `your upload` filter - what other filters are we looking at having?

**Comment by theefer** [comment]
People have asked for "has crops" and/or "has been used", although worth researching whether that's a proxy demand for something else, or whether it makes sense or not and how.

**Comment by jamesgorrie** [comment]
Why not arrow and words on wide vs filter icon on thin?

**Comment by theefer** [comment]
Yes sorry that what it does:

image

image

I find the first one weird but if people are happy I don't mind.

**Comment by theefer** [comment]
Redid a big of the responsive disclosure of controls, including adaptive width, icon, etc.

recorded

**Comment by theefer** [comment]
Note that even without people using this on mobile phones, it makes it usable in the Matt W case described on Slack where people have small windows to watch out for new images on a search term.

**Comment by paperboyo** [comment]
> People have asked for "has crops" and/or "has been used", although worth researching whether that's a proxy demand for something else, or whether it makes sense or not and how.

I started this small doc here, never finished, though: https://docs.google.com/document/d/1-9YI4mqIO3V3NYHtvuo8l23mH-sZy9MvP4Uah-Kmfs4/edit

> Only question is whether having both the expander arrow and an icon looks weird (hint: it does)

I agree, it does. But I'm at a loss to think of the way I'm entirely happy with. Having an icon there the whole time for users to get used to is important. Consistency in having expanders where there is a popup as well. But it looks odd :disappointed:

**Comment by jamesgorrie** [comment]
I'd remove the > :+1:

**Comment by theefer** [comment]
Removed the expander arrow, will merge as soon as orderby PR is on PROD.

**Pull request merged**
