### PR TITLE
refactoring gr-panel -> gr-info-panel

### PR DESCRIPTION
**Pull request by akash1810**
With the aim of fixing the issue of the disappearing info panel, refactor to a less confusing name.

Similar refactoring for the CSS on the way.

### CODE REVIEW

**Comment by theefer** [comment]
:+1:

**Comment by paperboyo** [comment]
Is there a reason why the LHS panel rememebers state via localstorage, but not the RHS one?

**Comment by akash1810** [comment]
@paperboyo no ones asked for it to ;) What state would it remember?

**Comment by paperboyo** [comment]
I haven't asked for something?! I can't believe it ;-)

It should remember exactly the same states that Collection panel does, I think. No? Not this PR, obviously, just piggybacking, 'cause slightly related...

**Comment by akash1810** [comment]
Ah, so locked/unlocked? And not scroll position (this won't be useful in this context).

We haven't remembered locked/unlocked thus far to give as much space to the thumbnails as possible. We could revisit if there's a demand - I'll take a look at the metrics for panel toggling.

**Comment by paperboyo** [comment]
Thanks. I think consistency would be nice to have in these devices (although, I agree about the scroll position!).

**Comment by akash1810** [comment]
> I'll take a look at the metrics for panel toggling.

We're not recording this :cry:.

**Pull request merged**
