### PR TITLE
🍟🍟🍟🍟🍟🍟 hasCrops chip 🍟🍟🍟🍟🍟

### PR DESCRIPTION
**Pull request by akash1810**
image

### CODE REVIEW

**Comment by akash1810** [comment]
Ideally, the presence of `hasCrops` would indicate `true`, similar to html attributes, but that's a bigger change...

**Comment by shaundillon** [comment]
It looks weird in camelcase

**Comment by paperboyo** [comment]
Oh, oh, oh... true/false just repeats +/- so is redundant.

Would it not be betterer to has a chip `has:` with a value `crops`?
We would then one day extend it to cover other values, like e.g. `leases`, `icc profile`, `transparency` etc.

**Comment by akash1810** [comment]
> Would it not be betterer to has a chip has: with a value crops?

Completely agree, but that's a bigger bit of work, which we can do afterwards.

> Oh, oh, oh... true/false just repeats +/- so is redundant.

👍 https://github.com/guardian/grid/pull/2187#issuecomment-399160862

**Pull request closed without merging**
