### PR TITLE
hover state and title on clear query button.

### PR DESCRIPTION
**Pull request by akash1810**
hover-clear-query

### CODE REVIEW

**Comment by theefer** [comment]
Is the hover state really necessary? The cursor already changes and it looks a bit weird. Also it overlays over the border.

**Comment by akash1810** [comment]
> Is the hover state really necessary? 

Thought it makes it uniform with the rest of the buttons across the site.

**Comment by theefer** [comment]
But it's not really the same button style as elsewhere; the others have a border all around, which makes the background colour less weird than if there is no border. Not a biggie but seems inelegant and superfluous to me in this instance.

**Comment by akash1810** [comment]
> the others have a border all around, which makes the background colour less weird than if there is no border

Agreed. What about treating it similar to batch label buttons (apply/delete from all images):

hover-clear-query

**Comment by alastairjardine** [comment]
The other option, and the one I actually prefer, is to give the control a bit more weight. What about this?
https://www.google.com/design/icons/#ic_highlight_off

Full area still clickable, of course

**Comment by alastairjardine** [comment]
Or https://www.google.com/design/icons/#ic_cancel @akash1810 

The added weightiness would be good here, especially as it's on quite a dark background.

**Comment by theefer** [comment]
As long as we don't introduce inconsistency (currently same clear for clearing search and selection and cancelling an edit etc).

**Comment by alastairjardine** [comment]
The bolder control works well in this context – I don't view it as an inconsistency in this case. Context matters :)

**Comment by akash1810** [comment]
to confirm - no hover state, but different icon?

**Comment by alastairjardine** [comment]
hover state on different icon – make it blue?

**Comment by akash1810** [comment]
updated (obv. you can't screen shot the mouse cursor...):

screen shot 2015-08-21 at 15 15 46

**Comment by akash1810** [comment]
Changed to white as its our main hover colour (see toolbar hover states).

Related https://github.com/guardian/grid/pull/1135.

**Comment by jamesgorrie** [comment]
:+1:

**Pull request merged**
