### PR TITLE
Improve top bar styling

### PR DESCRIPTION
**Pull request by rhystmills**
## What does this change?

This PR introduces some improvements to the top bar UI, specifically:
- Centres the checkbox and its label vertically
- Changes the cursor to a pointer when hovering over the checkbox items
- Stops the date order buttons changing size on click (using default browser styling for the focus ring (outline rather than a custom border)
- Stops the date range button causing a layout shift on click
- Add hover states to all the buttons
- Only show the focus ring for the date ordering buttons on tab, not click
- Style the download button consistently with the crop button (i.e. entire button highlighted, not just text)
- Make more of the top menu and results toolbar text labels align with each other

**Before:**

**After:**

## How should a reviewer test this change?

Run Grid locally according to the instructions in the readme. Does the top bar display as intended?

## Tested? Documented?
- [X] locally by committer
- [ ] locally by Guardian reviewer
- [ ] on the Guardian's TEST environment
- [ ] relevant documentation added or amended (if needed)

### CODE REVIEW

**Comment by paperboyo** [comment]
Bombastisch! One thingie: we seem to have lost the selected state for the sort order (which is also used for crop types etc):
  PROD:
  image
  This:
  image

**Comment by rhystmills** [comment]
> Bombastisch! One thingie: we seem to have lost the selected state background colour for the sort order (which is also used for crop types etc): PROD: image This: image

Ah, good spot. Should now be sorted.

**Comment by rhystmills** [comment]
Also centred the filters shown on smaller windows, with the hover state on the right:
image

**Comment by paperboyo** [comment]
Thx! Highlight has not got into a Crop page:

sdfsdfsdfsdf

**Comment by rhystmills** [comment]
> Thx! Highlight has not got into a Crop page:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196231629-6351ebdc-dbe4-4db4-a409-9fca2154ba3f.gif) [ ](https://user-images.githubusercontent.com/6032869/196231629-6351ebdc-dbe4-4db4-a409-9fca2154ba3f.gif)
> 
> or tabs in Info panel (sorry, missed them first time!):
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196232016-67732314-674a-4e89-a846-065bb94d0bf3.gif) [ ](https://user-images.githubusercontent.com/6032869/196232016-67732314-674a-4e89-a846-065bb94d0bf3.gif)

Also now done. I'm keen to fix any other sticking points but want to make sure the scope of the PR doesn't get too expansive. I did restyle the download button to match the crop one though.

**Comment by paperboyo** [comment]
> I did restyle the download button to match

Looking at how stupid it looks currently, this deserves a medal on its own: 🏅. I must have blocked the part of my brain that was looking at it for years…

> make sure the scope of the PR doesn't get too expansive

👍  Will put on TEST now.

**Comment by paperboyo** [comment]
Download button lost Download low res chevron/option, so exhibits an unusual margin:

sdfsdfsdfsdf

It’s there for multiple selection, where extra space disappears:

sdfsdfsdfsdf

Compare above to PROD:

sdfsdfsdfsdf

sdfsdfsdfsdf

Now. I have a suspicion that the whole Download low res functionality should just die and a chevron-within-a-button that is giving us headache here with it. But I guess it’ś a bigger job than just reverting the changes to make it a button (or – making a chevron work within a button for both single and multi-select).

Download low res was created for some users who needed lower resolution images to upload to some social media tool. Somewhen around 1973. I bet not a single person has used it genuinely since then. And you can quote me on that when they come complaining we removed it.

**Comment by rhystmills** [comment]
> Download button lost Download low res chevron/option, so exhibits an unusual margin:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557032-de23f64b-5110-4f37-8a3e-305ecccbaad6.gif) [ ](https://user-images.githubusercontent.com/6032869/196557032-de23f64b-5110-4f37-8a3e-305ecccbaad6.gif)
> 
> It’s there for multiple selection, where extra space disappears:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557313-b54339f3-ad38-451d-833c-6a38a6d7a7c2.gif) [ ](https://user-images.githubusercontent.com/6032869/196557313-b54339f3-ad38-451d-833c-6a38a6d7a7c2.gif)
> 
> Compare above to PROD:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557432-c9752181-77cc-4381-a243-e4fbaa603466.gif) [ ](https://user-images.githubusercontent.com/6032869/196557432-c9752181-77cc-4381-a243-e4fbaa603466.gif)
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557525-96249e76-48cf-4e81-931a-4a7af6fb642d.gif) [ ](https://user-images.githubusercontent.com/6032869/196557525-96249e76-48cf-4e81-931a-4a7af6fb642d.gif)
> 
> Now. I have a suspicion that the whole Download low res functionality should just die and a chevron-within-a-button that is giving us headache here with it. But I guess it’ś a bigger job than just reverting the changes to make it a button (or – making a chevron work within a button for both single and multi-select).
> 
> Download low res was created for some users who needed lower resolution images to upload to some social media tool. Somewhen around 1973. I bet not a single person has used it genuinely since then. And you can quote me on that when they come complaining we removed it.

We deployed the latest main to TEST and it turns out the download low res option doesn't show up there, for reasons we don't know.

**Comment by rhystmills** [comment]
> Download button lost Download low res chevron/option, so exhibits an unusual margin:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557032-de23f64b-5110-4f37-8a3e-305ecccbaad6.gif) [ ](https://user-images.githubusercontent.com/6032869/196557032-de23f64b-5110-4f37-8a3e-305ecccbaad6.gif)
> 
> It’s there for multiple selection, where extra space disappears:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557313-b54339f3-ad38-451d-833c-6a38a6d7a7c2.gif) [ ](https://user-images.githubusercontent.com/6032869/196557313-b54339f3-ad38-451d-833c-6a38a6d7a7c2.gif)
> 
> Compare above to PROD:
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557432-c9752181-77cc-4381-a243-e4fbaa603466.gif) [ ](https://user-images.githubusercontent.com/6032869/196557432-c9752181-77cc-4381-a243-e4fbaa603466.gif)
> 
> sdfsdfsdfsdf [ sdfsdfsdfsdf ](https://user-images.githubusercontent.com/6032869/196557525-96249e76-48cf-4e81-931a-4a7af6fb642d.gif) [ ](https://user-images.githubusercontent.com/6032869/196557525-96249e76-48cf-4e81-931a-4a7af6fb642d.gif)
> 
> Now. I have a suspicion that the whole Download low res functionality should just die and a chevron-within-a-button that is giving us headache here with it. But I guess it’ś a bigger job than just reverting the changes to make it a button (or – making a chevron work within a button for both single and multi-select).
> 
> Download low res was created for some users who needed lower resolution images to upload to some social media tool. Somewhen around 1973. I bet not a single person has used it genuinely since then. And you can quote me on that when they come complaining we removed it.

We deployed the latest main to TEST and it turns out the download low res option doesn't show up there, for reasons we don't know.

**Review by phillipbarron — COMMENTED** [review]
Regarding the download link - we (I) broke this by moving the padding to the container span. removing the `side-padded` class from the root div in the [gr-downloader](https://github.com/guardian/grid/blob/main/kahuna/public/js/components/gr-downloader/gr-downloader.html#L1) and adding it to each on the buttons & the link will fix that. 
Removing the low-res chevon / functionality is probbaly sensible since it's not used - it's a tiny change. Example PR: https://github.com/guardian/grid/pull/3905

**Comment by rhystmills** [comment]
> Regarding the download link - we (I) broke this by moving the padding to the container span. removing the `side-padded` class from the root div in the [gr-downloader](https://github.com/guardian/grid/blob/main/kahuna/public/js/components/gr-downloader/gr-downloader.html#L1) and adding it to each on the buttons & the link will fix that. Removing the low-res chevon / functionality is probably sensible since it's not used - it's a tiny change. Example PR: #3905

Cheers for the heads up! That's now sorted.

**Comment by andrew-nowak** [comment]
1. on the image details page: there's still a chevron/dropdown when the config option `canDownloadCrop` is set to true and you click "into" a crop - it's close to the edge of the download box (and overlaps its neighbour) 
image
 
2. on the results page: when an image has a fullframe crop the text in the disabled button is out of alignment 
image
(I can't quite tell, but I think the download and delete buttons have wider margins on the search results page too)

(side note, but the crop and download buttons feel very similar (can be disabled, may have chevron/dropdown of extra options), and like there should be a shared component to manage how they get presented... which we might find easier to implement in React...)

**Comment by rhystmills** [comment]
> 1. on the image details page: there's still a chevron/dropdown when the config option `canDownloadCrop` is set to true and you click "into" a crop - it's close to the edge of the download box (and overlaps its neighbour)
> 
> image
> 
> 2. on the results page: when an image has a fullframe crop the text in the disabled button is out of alignment
> 
> image
> 
> (I can't quite tell, but I think the download and delete buttons have wider margins on the search results page too)
> (side note, but the crop and download buttons feel very similar (can be disabled, may have chevron/dropdown of extra options), and like there should be a shared component to manage how they get presented... which we might find easier to implement in React...)

The chevron and double margin issues should be fixed now.

The React suggestion is a good one but I will avoid doing so in this PR to keep the scope limited.

**Review by andrew-nowak — APPROVED** [review]
it's beautiful!

**Pull request merged**
