### PR TITLE
Feature/add people in image metadata

### PR DESCRIPTION
**Pull request by jamie-pitts**
Note: This PR requires https://github.com/guardian/grid/pull/2664 to be merged first.
**As this adds a new mapping into ES the `UpdateMapping` command will need to be run against the ES index first.** (this is just adding a new field and not editing existing ones, so relatively safe/easy)

## What does this change?

This adds a new field `peopleInImage` to the metadata of the image. It extracts from the XMP fields: `Iptc4xmpExt:PersonInImage` and `GettyImagesGIFT:Personality` - more can easily be added if/when found. 

The following is an example of the metadata section in the api response after uploading an image which includes the person in image metadata:
```
  "metadata": {
    "dateTaken": "2019-10-24T15:09:53.460Z",
    "description": "TOKYO, JAPAN - OCTOBER 24: Kieran Read, Scott Barrett, Aaron Smith, Codie Taylor and Shannon Frizell of the All Blacks stretch during a New Zealand All Blacks training session at Tatsuminomori Seaside Park on October 24, 2019 in Tokyo, Japan. (Photo by Hannah Peters/Getty Images)",
    "credit": "Getty Images",
    "byline": "Hannah Peters",
    "bylineTitle": "Staff",
    "title": "New Zealand Media Access",
    "copyrightNotice": "2019 Getty Images",
    "copyright": "2019 Getty Images",
    "suppliersReference": "775424562",
    "source": "Getty Images AsiaPac",
    "specialInstructions": "All use in books (including autobiographies) or magazines, which are entirely dedicated to any and/or all RWCL competitions and/or Matches requires separate written approval from Rugby World Cup Limited.",
    "keywords": [
      "sport",
      "rugby",
      "rugby union",
      "rugby union world cup",
      "rugby union world cup 2019",
      "all blacks - rugby team",
      "bestof",
      "topix"
    ],
    "city": "Tokyo",
    "country": "Japan",
    "subjects": [
      "sport"
    ],
    "peopleInImage": [
      "Codie Taylor",
      "Aaron Smith",
      "Shannon Frizell",
      "Kieran Read",
      "Scott Barrett"
    ]
  }
```

This will be the first PR in a series of PRs to add functionality to search for people who are in an image, and to display who is in an image in the metadata section of the UI.

### CODE REVIEW

**Comment by mbarton** [comment]
@paperboyo would you have an example image that has the XMP fields so we can test this PR?

**Comment by paperboyo** [comment]
`[domain]search?query=has:fileMetadata.xmp.Iptc4xmpExt:PersonInImage%5B1%5D&nonFree=true`
&
`[domain]search?query=has:fileMetadata.xmp.GettyImagesGIFT:Personality%5B1%5D&nonFree=true`

**Comment by mbarton** [comment]
As @paperboyo just commented, we'll take an image that has this metadata field from our current prod deployment (by using the search above) and then upload it into our test environment with this PR deployed

**Comment by AWare** [comment]
This has been merged in https://github.com/guardian/grid/pull/2956

**Pull request closed without merging**
