### PR TITLE
clearer Collections edit button states

### PR DESCRIPTION
**Pull request by akash1810**
Making it more obvious what state you're in.

# Before
edit-button-before

# After
edit-button

### CODE REVIEW

**Comment by theefer** [comment]
Cool. Is the Edit button an existing button style we use elsewhere? (The Finished style seems to be?)

**Comment by akash1810** [comment]
Edit button is new. Or rather its a duplicate of `.button-cancel` with a more relevant name for the context its used in. The finished style is `.button-save` which has sensible nomenclature in this context.

**Comment by tsop14** [comment]
I like it - much more obvious. Re. styling, should it be full heigh like the 'clear selection', 'add to library' et al. that appear in the top bar?  I suppose it is signalling a mode that you are in, so maybe different from them.

**Comment by akash1810** [comment]
> Re. styling, should it be full heigh like the 'clear selection', 'add to library' et al. that appear in the top bar?

Tried that but a full height blue button looked a bit odd. We're also following the styling of the "new images" button here, which is blue and not full height.

**Comment by tsop14** [comment]
:+1:

**Pull request merged**
