### PR TITLE
delete all indexes of collections in dynamo

### PR DESCRIPTION
**Pull request by jamesgorrie**
As we just add to the list of collections in dynamo (we can have two entries for one collection) - we need to make sure we delete all references to the path - this does that.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@tsop14 this should stop the bug you were having of having to hit delete multiple times.

**Comment by theefer** [comment]
Any way we can also prevent duplicates when adding multiple times?

**Comment by theefer** [comment]
:+1:

**Comment by jamesgorrie** [comment]
> Any way we can also prevent duplicates when adding multiple times?

It was a decision to just keep all of them - which can be useful with something like an audit trail.

We could:
`Read => override duplicate with new `actionData` => write`, but I didn't see the need to read before as we could just use Dynamos `list_append` syntax.

**Comment by theefer** [comment]
:+1: OK as not exposed through ES

**Pull request merged**
