### PR TITLE
Add extra info to readme, make stack-name script work on os x

### PR DESCRIPTION
**Pull request by philmcmahon**
Hopefully should help the next person.

### CODE REVIEW

**Comment by NickPapacostas** [comment]
@akash1810 i remember there was some complexity about this but i can't remember what >.< I thought we didn't need permanent credz

**Comment by akash1810** [comment]
> I thought we didn't need permanent credz

Sort of. You can't call IAM methods over the CLI with Janus credentials. You can, however in the web console.

Might be better to remove these scripts entirely in favour of "use the cfn json template to create a stack" to avoid confusion?

**Comment by akash1810** [comment]
> Might be better to remove these scripts entirely in favour of "use the cfn json template to create a stack" to avoid confusion?

https://github.com/guardian/grid/pull/1893 made some effort to do this; if you create a file in `~/.gu/grid/dev_stack_name` an IAM call won't be made.

**Comment by philmcmahon** [comment]
I guess we could make the cfn script create /grid/dev_stack_name (if it doesn't already) and then I can update my note to just say 'make sure dev_stack_name exists'

**Pull request merged**
