### PR TITLE
Support API params for filtering by date modified/taken since/until

### PR DESCRIPTION
**Pull request by theefer**
Also retired the fromDate/toDate which was redundant with since/until.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Good to watch performance on these as the ordering was a little slower (I'm just wondering how ES deals with dates).

:+1:

**Comment by theefer** [comment]
> as the ordering was a little slower

Where did you see that? Just curious as I don't think the current ordering field (`uploadTime`) is indexed specially?

**Comment by jamesgorrie** [comment]
I remember @akash1810 saying it and also in the demo this morning, although that could have been the wifi.

**Comment by akash1810** [comment]
The inclusion of the `offset` param makes the performance a little worse.

`https://api.[domian]/images?q=&offset=1649680&length=1&orderBy=uploadTime&free=true`

vs 

`https://api.[domain]/images?q=length=1&orderBy=uploadTime&free=true`

**Comment by theefer** [comment]
I don't think this has anything to do with the existing performance issue, so merging.

**Pull request merged**
