### PR TITLE
Usage rights: Order select boxes (e.g. photographer name)

### PR DESCRIPTION
**Pull request by kenoir**
It should be ordered rather than random

screen shot 2015-07-17 at 10 09 57

### CODE REVIEW

**Comment by kenoir** [comment]
crop

**Comment by akash1810** [comment]
Should we order by surname?

**Comment by kenoir** [comment]
@akash1810 Might be impossible given the underlying implementation.

**Comment by paperboyo** [comment]
> Should we order by surname?

There aren't (will never be) that many... although "everybody is a photographer now" :wink: Also, new Editorial Users server sorts __all__ users by first name, haha.

**Comment by akash1810** [comment]
> Might be impossible really annoying to implement given the underlying implementation.

Could do some funky split on ' ' then move the last index to the first and sort... but horrible.

:+1:

**Comment by jamesgorrie** [comment]
:-1: Bad implementation - we're looking at shifting all logic to the server.

**Comment by kenoir** [comment]
Meh :crying_cat_face:

**Comment by jamesgorrie** [comment]
not fussed :+1:

**Pull request closed without merging**
