### PR TITLE
write filename to description if no description in image metadata

### PR DESCRIPTION
**Pull request by akash1810**
Fixes https://github.com/guardian/grid/issues/1459.

### CODE REVIEW

**Comment by tsop14** [comment]
This was being done before #937 - was it removed or did it break?

**Comment by akash1810** [comment]
> This was being done before #937

That PR was only setting the value on the client and wan't making a request to the metadata-editor to save it.

**Comment by tsop14** [comment]
> Neither - it just didn't exist :smile:.

Until now... :+1:

**Comment by theefer** [comment]
Cool. @NickPapacostas had already started working on this I think, my bad, so maybe we need to communicate more around who's working on what, either via GitHub issues or Slack or vocal-chord-chat.

**Comment by akash1810** [comment]
ah. +1 for more comms!

**Pull request merged**
