### PR TITLE
persist illustrators.

### PR DESCRIPTION
**Pull request by akash1810**

### CODE REVIEW

**Comment by jamesgorrie** [comment]
Did we need to add this into ES anywhere?
I can't remember if we query on `isPersisted`?

**Comment by akash1810** [comment]
good catch! 1 sec...

**Comment by akash1810** [comment]
> Did we need to add this into ES anywhere?

Done now.

(Probably time to write tests now...)

**Comment by jamesgorrie** [comment]
:+1:

**Comment by theefer** [comment]
:+1:

**Pull request merged**
