### PR TITLE
Remove redundant copyrightNotice field

### PR DESCRIPTION
**Pull request by paperboyo**
NB: this does not require an immediate remapping, as we'll no longer be passing the `copyrightNotice` field into Elasticsearch; you'd need to remap before a reindex, though, to ensure that index is removed on existing images.

## What does this change?
This removes copyrightNotice field as this is an [equivalent of copyright](https://www.iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#copyright-notice). It also reconciles copyright correctly (XMP>IPTC>EXIF). It also makes copyright cleaner only apply to byline and credit fields as copyright is the field that holds a statement of rights and we shouldn’t mess around with its contents just because it can be inconsistent, even more so, because we don’t use it anywhere that would require it to be cleaned or consistent.

## How can success be measured?
No useless fields.

## Tested?
- [ ] locally
- [x] on TEST

### CODE REVIEW

**Comment by jennygrahamjones** [comment]
> This requires remapping!
Does this mean there is some action required in addition to merging the PR?

**Comment by paperboyo** [comment]
> Does this mean there is some action required in addition to merging the PR?

That’s my understanding, reading the note at the beginning of https://github.com/guardian/grid/pull/2667. Similarly, [this one](https://github.com/guardian/grid/pull/2716) may need one too (analyzers change). Will discuss and won’t merge myself!

**Comment by paperboyo** [comment]
[[mappings change] copyright and copyrightNotice should be one field](https://trello.com/c/aguHJcul/1632-mappings-change-copyright-and-copyrightnotice-should-be-one-field)

**Comment by akash1810** [comment]
This change drops a property from documents in ES. I think it should be safe to merge this w/out remapping. We should test on TEST first though!

**Review by jonathonherbert — APPROVED** [review]
Been through the problem and code w/ @paperboyo and all looks good. Presume this is tested in CODE, Mat, v. happy to test if not.

**Comment by paperboyo** [comment]
> Presume this is tested in CODE

Yep. Just sent an email, if we don’t hear anything, will merge. Thx!

**Pull request merged**
