### PR TITLE
Moves simple ordering to search bar (use checkbox for binary state)

### PR DESCRIPTION
**Pull request by kenoir**
gifrecord_2015-08-19_155119

### CODE REVIEW

**Comment by kenoir** [comment]
@alastairjardine preparation for moving more options to subnav.

**Comment by alastairjardine** [comment]
All good – I like the visual nature of the previous style, but happy for it to go out like this for now!

**Comment by theefer** [comment]
:-1: from me, I find it really confusing to be a checkbox and to be placed in the middle of filtering options. It's also not very future proof as we have discussed allowing to order by last modified too.

Happy to chat and/or be proven wrong.

**Comment by alastairjardine** [comment]
Could we, for kicks, try the previous style buttons up there instead?

**Comment by kenoir** [comment]
@theefer @alastairjardine continuing this work in https://github.com/guardian/grid/pull/1110.

**Pull request closed without merging**
