### PR TITLE
Fix close button position, use clear icon

### PR DESCRIPTION
**Pull request by theefer**
# Before

image

# After

screenshot-2015-08-20t16 33 48

### CODE REVIEW

**Comment by akash1810** [comment]
:+1:

**Comment by alastairjardine** [comment]
Great. Just checking a usability detail: Is the square-area clickable or only the ✖ detail?

**Comment by theefer** [comment]
It's larger than the X, thought not quite the whole area.

Actually here was easy change so I just fixed it to be the full area, see dark outline:

image

**Comment by alastairjardine** [comment]
Perfect @theefer

**Pull request merged**
