### PR TITLE
add filename search as a chip

### PR DESCRIPTION
**Pull request by akash1810**
This will make it easier to debug errors from s3 watcher.

image

### CODE REVIEW

**Comment by paperboyo** [comment]
Great! I wanted this for... like... [3 years](https://github.com/guardian/grid/pull/937#issuecomment-121681833).

More “debugging” chips I say!

**Comment by paperboyo** [comment]
For the future: this (and maybe all chips) should accept wildcards...

**Comment by akash1810** [comment]
> For the future: this (and maybe all chips) should accept wildcards...

Interesting. Do you have an example where this should apply?

**Comment by paperboyo** [comment]
I try not to let me sick mind wonder where there are no examples. As with all things search/filter, this applies in the same way to Grid, Open Explorer, Bubbles (@currysoup 👋) and all else. If I would like to appear just a little bit facetious, I would say it wouldn’t exactly hurt to have it in dotcom too. Applies to fields AND to values.

_(Baby-syntax for wildcards/broken regex/stupid mix. I don’t care much for which is chosen as long as there is an easily accessible help where I will be learning it all over again every single time.)_

- `filename:Screen Shot*.png` (matches all OSX screenshots)
- `filename:_MG*.jpg −has:fileMetadata.icc` (finds candidates for [straight from Canon JPGs in AdobeRGB](https://github.com/guardian/grid/issues/2066))
- `filename:\d*tomWimbledon5jul18.jpg` (finds recent Tom Jenkins’ shoot)
- `filename:.*_modified\..{3,4}` `OR` `filename:\1\..{3,4}` (finds all occurrences where paperboyo tries to workaround the lack of Versions: originals and modified images)
- `fileMetadata:icc.Profile Description."sRGB*"` `OR` `fileMetadata:xmp.photoshop:ICCProfile."sRGB*"` (finds all images with whatever crazy flavour of sRGB profile there is)
- `fileMetadata:xmp.dc:creator["\d*"]` (finds images with any number of Creator entries)
- `fileMetadata:exifSub.Lens Specification."*-*"` (finds images taken with a zoom lens)
- `fileMetadata:xmp.dc.*` (finds all images with any Dublin Core properties)

All this combined with filters showing no. of hits next to properties (and an extra free-text filter for entering the property you’re interested in*) should make most librarians blush.

*to explain, imagine:
- a search `by:Tom Jenkins` and a filter sidebar where for a free-text filter you enter `filename:\d*.*.jpg`
(should return a list of shoots sorted by the number of photos in each shoot (provided he is consistent in his naming scheme. And provided someone fixes my baby-regex)
- a search `fileMetadata:xmp.dc:creator["\d*"]` and a free-text filter containing `fileMetadata:xmp.dc:creator*` (lists images with distribution of Creator entries)

I could go on. How useful any of that would be? How popular? I’m not paid to care seriously for such questions. Luckily.

**Pull request merged**
