### PR TITLE
cropperjs

### PR DESCRIPTION
**Pull request by tsop14**
Swaps jcrop for cropperjs - the overrides which should be in jspm [registry](https://github.com/jspm/registry/pull/835) soon. 

Lovely centre marker.
Beautiful cropbox guide lines.
Dashing blue cropbox outline. 

Adds ability to set dimensions. 
cropperjs

Makes aspect buttons responsive - still overflows on very small window. 
screen shot 2016-03-31 at 17 25 48

before: 
screen shot 2016-03-31 at 17 25 32

! The image on the crop page is low quality
screen shot 2016-03-31 at 17 51 30

Compared to current image: 
screen shot 2016-03-31 at 17 51 34

### CODE REVIEW

**Comment by tsop14** [comment]
Should the crop be full width by default? 😕

**Comment by kenoir** [comment]
Maybe. I think we'd talked about it? Probably in this PR it should just be
the same as it is now.
On Thu, 31 Mar 2016 at 18:14, Emma Milner <notifications@github.com> wrote:

> Should the crop be full width by default? 😕
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/grid/pull/1831#issuecomment-204028321>
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by kenoir** [comment]
@tsop14 yes.

**Comment by kenoir** [comment]
:+1:

**Comment by jamesgorrie** [comment]
> Dashing blue cropbox outline.

:boom:

**Pull request merged**
